#!/usr/bin/bash
LGREEN=$(echo '\033[01;32m')

clear

#-------Atualizar Repositório e o Sistema-------#
echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Atualizar Repositorios║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"

sleep 1s

sudo xbps-install -S void-repo-multilib-nonfree void-repo-multilib void-repo-nonfree

echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Atualizar Sistema║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"
sudo xbps-install -Su

sleep 1s

clear


#--------------Xorg Minimo--------------#


echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Instalando Xorg Minimo║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"

#-------Edite para o driver que você possui-------#

xbps-install -S xorg-server

#xbps-install -S xf86-video-intel

#xbps-install -S xf86-video-nouveau

#xbps-install -S xf86-video-openchrome

#xbps-install -S xf86-video-amdgpu

#xbps-install -S xf86-video-ati

xbps-install -S xf86-video-fbdev

xbps-install -S xf86-input-libinput

xbps-install -S xinit

xbps-install -S xorg-setxkbmap

xbps-install -S xorg-fonts

xbps-install -S xsetroot

sleep 1s

clear


#--------------BSPWM--------------

echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Instalando Pacotes Basicos BSPWM║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"

sudo xbps-install bspwm sxhkd xsetroot urxvt dmenu

clear	

sleep 1s

#------Configurando arquivos de configuração------#

echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Configurando Arquivos║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"

mkdir -p ~/.config/{bspwm,sxhkd}

cp /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm

cp /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd

echo "xsetroot -cursor_name left_ptr &" >> ~/.config/bspwm/bspwmrc
	
echo "nitrogen --restore &" >> ~/.config/bspwm/bspwmrc

sleep 1s

clear

#-----Instalando Aplicações Básicas----#

echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Instalando Aplicacoes Basicas║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"

sudo xbps-install -S base-devel git vim

sudo xbps-install -S lxappearance

sudo xbps-install -S nitrogen

sudo xbps-install -S firefox firefox-i18n-pt-BR

sudo xbps-install -S pulseaudio

sudo xbps-install -S pavucontrol

sudo xbps-install -S NetworkManager

sleep 1s

clear

#-----Configurando Serviços----#

echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Configurando Serviços║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"

ln -s /etc/sv/dbus /var/service/

ln -s /etc/sv/pulseaudio /var/service/

ln -s /etc/sv/NetworkManager /var/service/

sleep 1s

clear

echo "${LGREEN}╓╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╖"
echo "║Instalação Concluida!║"
echo "╙╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╾╜${LGREEN}"

sleep 2s

clear
