#!/bin/sh

clear

#-------Atualizar Repositório e o Sistema-------#

echo "╓══════════════════════╖"
echo "║Atualizar Repositorios║"
echo "╙══════════════════════╜"

sleep 1s

sudo xbps-install -S void-repo-multilib-nonfree void-repo-multilib void-repo-nonfree

echo "╓═════════════════╖"
echo "║Atualizar Sistema║"
echo "╙═════════════════╜"
sudo xbps-install -Su

sleep 1s

clear


#--------------Xorg Minimo--------------#

echo "╓══════════════════════╖"
echo "║Instalando Xorg Minimo║"
echo "╙══════════════════════╜"

#-------Edite para o driver que você possui-------#

sudo xbps-install -S xorg-server

#sudo xbps-install -S xf86-video-intel

#sudo xbps-install -S xf86-video-nouveau

#sudo xbps-install -S xf86-video-openchrome

#sudo xbps-install -S xf86-video-amdgpu

#sudo xbps-install -S xf86-video-ati

sudo xbps-install -S xf86-video-fbdev

sudo xbps-install -S xf86-input-libinput

sudo xbps-install -S xinit

sudo xbps-install -S setxkbmap

sudo xbps-install -S xorg-fonts

sudo xbps-install -S xsetroot

sleep 1s

clear


#--------------BSPWM--------------

echo "╓════════════════════════════════╖"
echo "║Instalando Pacotes Basicos BSPWM║"
echo "╙════════════════════════════════╜"

sudo xbps-install bspwm 

sudo xbps-install sxhkd

sudo xbps-install rxvt-unicode

sudo xbps-install dmenu	

sleep 1s

clear

#------Configurando arquivos de configuração------#

echo "╓═════════════════════╖"
echo "║Configurando Arquivos║"
echo "╙═════════════════════╜"

mkdir -p ~/.config/{bspwm,sxhkd}

cp /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm

cp /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd

cp /usr/X11/xinit/xinitrc ~/.xinitrc

echo "xsetroot -cursor_name left_ptr &" >> ~/.config/bspwm/bspwmrc
	
echo "nitrogen --restore &" >> ~/.config/bspwm/bspwmrc

echo "exec bspwm" >> .xinitrc

sleep 3s

clear

#-----Instalando Aplicações Básicas----#

echo "╓═════════════════════════════╖"
echo "║Instalando Aplicacoes Basicas║"
echo "╙═════════════════════════════╜"

sudo xbps-install -S base-devel vim

sudo xbps-install -S lxappearance

sudo xbps-install -S nitrogen

sudo xbps-install -S firefox firefox-i18n-pt-BR

sudo xbps-install -S pulseaudio

sudo xbps-install -S pavucontrol

sudo xbps-install -S NetworkManager

sleep 1s

clear

#-----Configurando Serviços----#

echo "╓═════════════════════╖"
echo "║Configurando Serviços║"
echo "╙═════════════════════╜"

sudo ln -s /etc/sv/dbus /var/service/

sudo ln -s /etc/sv/pulseaudio /var/service/

sudo ln -s /etc/sv/NetworkManager /var/service/

sleep 3s

clear

#----Instalação Concluída!----#

echo "╓═════════════════════╖"
echo "║Instalação Concluida!║"
echo "╙═════════════════════╜"

sleep 2s

clear
